### ISSUE TITLE
Could this work on a Mac?

### ISSUE THREAD

**Issue by torntrousers** [nyumaya/nyumaya_audio_recognition#1]
I'm guessing it would need a Mac version of libnyumaya.so, how are they made?

**Comment by yodakohl** [comment]
They are compiled from a closed source repository. I will try to compile a lib for Mac, but this might take a few days.

**Comment by torntrousers** [comment]
That would be terrific, thank you so much.

**Comment by torntrousers** [comment]
Hello @yodakohl , just wondered if you'd manage to get anywhere with the Mac compile yet?

**Comment by yodakohl** [comment]
Compiling for MAC without a MAC seems pretty hard.  I decided to open source the library code so people will be able to compile the library themselves. I will have to do some minor cleanups and there might be some other work to do. Mainly providing a cross-platform interface for audio capturing (python-sounddevice) and I expect some hiccups with the python bindings.


2. Nov 2018 09:30 von notifications@github.com <mailto:notifications@github.com>:

**Comment by torntrousers** [comment]
Tremendous. I'd be happy to help you with that if there is anything you think I could do.
