### ISSUE TITLE
Respeaker far field hardware for RaspPi

### ISSUE THREAD

**Issue by jonsmirl** [nyumaya/nyumaya_audio_recognition#10]
Seeed makes a cheap ($25) 4-channel far field mic board for the Rasp Pi, you can buy it from Amazon or direct.  I have one is it works without issue. The four mics appear as a 4-channel ALSA device.

https://www.seeedstudio.com/ReSpeaker-4-Mic-Array-for-Raspberry-Pi-p-2941.html

A very useful addition would be instructions for replacing Snoboy with your keyword code in the Repeaker tutorial.

**Comment by yodakohl** [comment]
Thanks, I will try to do that.

**Comment by jonsmirl** [comment]
I have one of these on order, Playstation Eye. It is supposed to appear as a 4-channel USB microphone under Linux. AFAIK it is just a microphone, no processing is done locally. The idea is to get a mic array on my desktop for software development purposes.
https://www.amazon.de/Playstation-PS3-eyetoy-Kamera-Gro%C3%9Fpackung/dp/B00LME2JGQ/ref=sr_1_1

**Comment by yodakohl** [comment]
> Snoboy with your keyword code in the Repeaker tutorial.
Could you give me a hint where the Respeaker tutorial is? All tutorial links on their page seem dead for me.

**Comment by jonsmirl** [comment]
http://wiki.seeedstudio.com/ReSpeaker_4_Mic_Array_for_Raspberry_Pi/

**Comment by yodakohl** [comment]
Thanks, their repository is interesting.

It seems like they don't do any Beamforming but simply running the keyword detection for
each channel separately. 

(voice_engine/route.py
	
 for ch in range(src.channels):
	k = KWS(sensitivity=0.5)
	k.set_callback(gen(ch))
	kws.append(k)

They feed the snowboy detector with 16-bit int bytes which is already the matching format. To make it work for my recognition the only real modification would be chunking the input data to have the correct length. This can be easily done with my implementation in ringbuffer.py. Gonna try this soon.

**Comment by jonsmirl** [comment]
Their more complex code is in this repository
https://github.com/voice-engine/voice-engine

They do beamforming somewhere in their code, I will look around and see if I can spot  where it is.
