### ISSUE TITLE
Crowd Monitoring / Gun Shot Detection

### ISSUE THREAD

**Issue by TheUnriashol** [nyumaya/nyumaya_audio_recognition#16]
Hi there,
**Is your feature request related to a problem? Please describe.**
My request is based on the fact that I am looking to build a crowd monitor using a raspberry pi. The end game is to build a cluster of them but for now I am looking at the software itself. This is where I found your software but I saw that you have not implemented the feature of gun shot detection.

**Describe the solution you'd like**
I would like to know if it were possible that you could train the audio recognition to specifically detect gun shots and in general crowd commotions. 

**Describe alternatives you've considered**
I have considered looking at other software available but have not found any for raspberry pi or any other distribution in fact. I have also considered creating my own but even though I have quite a bit of knowledge about programming and Machine Learning, it is not enough for something like this.

**Additional context**
This is an idea I have for a project I am working on in my university and would really appreciate the help or any pointers you might have.

**Comment by yodakohl** [comment]
I will try to prioritize it but acoustic events models are delayed because the [freesound](https://datasets.freesound.org/fsd/) dataset is not released yet. For now I can try to train an experimental version with limited data and therefore limited accuracy.

**Comment by TheUnriashol** [comment]
> I will try to prioritize it but acoustic events models are delayed because the [freesound](https://datasets.freesound.org/fsd/) dataset is not released yet. For now I can try to train an experimental version with limited data and therefore limited accuracy.

Hi Neumair, that would be great, I really just simply wanted to know if it were possible. I would love if you could train an experimental version. Like I said the accuracy doesn't have to be perfect since it is only for a school project. I have been looking a lot over the internet and have even found forum/reddit threads that where filled with requests like this but nobody had a good solution. So if you could do it I would really appreciate it, since it would help me out quite a bit.

My main goal is specifically gun shot detection. So crowd commotion is not really that important to me, I just saw it in your possible features list.

Thank you!!!

**Comment by yodakohl** [comment]
Closing because experiental gun shot detection is up. Accuracy tests and improvements will follow later.

**Comment by mathematicalmichael** [comment]
I really appreciate this addition! Great library. I appreciate you don't want to take requests for custom training, but I'm wondering if you may already have something along the lines of "loud noise" (just a sudden change in volume). I'm thinking it could be pretty similar to gunshot detection, but I can't seem to get that model to trigger (even at 0.9 sensitivity). In some sense, I'm not sure a model is really even required, the network would effectively look like taking a first-order approximation to a derivative and assigning a threshold.
