### ISSUE TITLE
Can you add code to train custom models?

### ISSUE THREAD

**Issue by Alenorze** [nyumaya/nyumaya_audio_recognition#18]
Hello, I would like to try to train my own model, but I can not find the code for learning it in the repository, as I see the usual convolutional model is used here, could you publish the files for its learning, I want to try to train it on other devices with a small number of examples, I would not want to spend time repeating the structure of this. Thanks!

**Comment by yodakohl** [comment]
The training code is proprietary. 
If you need to train your own models you have to look for other solutions like [Simple Audio Recognition](https://www.tensorflow.org/tutorials/sequences/audio_recognition) or [Mycroft Precise](https://github.com/MycroftAI/mycroft-precise).

I will update the README to make this more clear.
