### ISSUE TITLE
Didn't find op for builtin opcode 'CONV_2D' version '2'

### ISSUE THREAD

**Issue by adishpv9** [nyumaya/nyumaya_audio_recognition#21]
**Describe the bug**
I converted my own speech recognition model to tflite and used with streaming.py.
That throws an error:
Didn't find op for builtin opcode 'CONV_2D' version '2'

Registration failed
Error creating interpreter
Segmentation fault

**To Reproduce**
Just run streaming.py with my tflite model

**Platform**
 - Raspberry Pi
 
**Additional context**
I am using raspberry pi zero W for this.

**Comment by yodakohl** [comment]
The tensorflow library from the master branch is quite old. Can you try checking out the V0.3.5 branch?
