### ISSUE TITLE
Hi, This is Hemsingh.  I like to more about Speech Recognition on Raspberry Pi . Mostly on Training on Google Colab. Please Help me .

### ISSUE THREAD

**Issue by hemsinghBanoth** [nyumaya/nyumaya_audio_recognition#22]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yodakohl** [comment]
There are plenty of tutorials available, eg: [here](https://www.digikey.com/en/maker/projects/tensorflow-lite-tutorial-part-1-wake-word-feature-extraction/54e1ce8520154081a58feb301ef9d87a)
