### ISSUE TITLE
[Q] What are the best free options on hotword detection?

### ISSUE THREAD

**Issue by NightMachinery** [nyumaya/nyumaya_audio_recognition#23]
Hi! Thanks for the project. I was wondering if you knew what the top-notch hotword detection options are? I used to use snips.ai, but they have since sold out.

**Comment by yodakohl** [comment]
Hi, I'm not aware of any free customized keyword provider. Making customized keyword spotting requires more effort than someone can do in his free time (were talking about years of development if you want to make a generic system). For custom solutions I'm happy to train keyword models in exchange for the audio data (2k samples from diverse speakers, no tts system ) . But acquiring this data usually takes multiple thousands of dollars.
