### ISSUE TITLE
training instructions?

### ISSUE THREAD

**Issue by JarbasAl** [nyumaya/nyumaya_audio_recognition#25]
i would like to train a few models to evaluate this lib, are there instructions available?

I made a plugin for [Mycroft](https://mycroft.ai/), see https://github.com/JarbasAl/numaya_hotword , training would be really important for community adoption

**Comment by yodakohl** [comment]
Hi,

If you send me a list of the keywords I can train them for you.

best Regards,

Günther

Nov 27, 2020, 09:57 by notifications@github.com:

**Comment by JarbasAl** [comment]
Hello

Thank you for the offer, it would be cool if you could train "hey mycroft", that way i could do some benchmarks against other wake word detector engines

However what i would like is instructions, users of the plugin linked above will want to train their own wake words, should i just point them to you? I'm more concerned with documentation than with getting wakewords for myself

Or is the training code closed source?

Thank you

**Comment by yodakohl** [comment]
Hi, 

I can train hey mycroft, but the training code is closed source.

Best Regards,
Günther


Nov 28, 2020, 13:15 by notifications@github.com:

**Comment by JarbasAl** [comment]
Thank you for the quick response, i will add that information to the readme in my plugin.

Will leave this issue open until you train "hey mycroft" wake word, but feel free to close it

Best Regards

**Comment by JarbasAl** [comment]
i humbly request yet another model for "wake up", that would be very useful to have

Thank you!

**Comment by yodakohl** [comment]
Added it to the list, eval model will be released together with the next version.

**Comment by yodakohl** [comment]
Eval models are available at http://nyumaya.com/models/V1.0.0_Jarabas.zip
For easier performance evaluation there will be a fork of the [wake-word-benchmark](https://github.com/Picovoice/wake-word-benchmark) [here](https://github.com/nyumaya/wake-word-benchmark). I'm currently pretty busy so this may take a couple of days before I can get to it.

**Comment by JarbasAl** [comment]
thank you for the models! So far i am quite impressed from the quick testing i made, i will do some proper benchmarking once i have some more free time. I haven't really looked into false activations, but when i say the wake words it seems to trigger almost always

keep up the good work! great performance and accuracy looks good
